import { createClient } from '@supabase/supabase-js'
import Link from 'next/link'
import { BookOpen, Play, LogOut, User } from 'lucide-react'

async function getDashboardData(slug: string) {
  const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
          process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
            )
              const { data: club } = await supabase.from('clubs').select('*').eq('slug', slug).single()
                if (!club) return { club: null, courses: [] }
                  const { data: courses } = await supabase.from('courses').select('*').eq('club_id', club.id).eq('active', true)
                    return { club, courses: courses || [] }
                    }

                    export default async function DashboardPage({ params }: { params: { slug: string } }) {
                      const { club, courses } = await getDashboardData(params.slug)
                        if (!club) return <div className="min-h-screen bg-black flex items-center justify-center text-white">Club nao encontrado</div>

                          return (
                              <div className="min-h-screen bg-zinc-950 text-white flex">
                                    <aside className="w-64 bg-zinc-900 border-r border-white/5 flex flex-col">
                                            <div className="p-6 border-b border-white/5">
                                                      <div className="flex items-center gap-3">
                                                                  <div className="w-10 h-10 rounded-full flex items-center justify-center font-bold text-lg" style={{ backgroundColor: club.primary_color || '#3b82f6' }}>
                                                                                {club.name[0]}
                                                                                            </div>
                                                                                                        <div>
                                                                                                                      <h2 className="font-bold text-sm">{club.name}</h2>
                                                                                                                                    <p className="text-zinc-500 text-xs">Area de Membros</p>
                                                                                                                                                </div>
                                                                                                                                                          </div>
                                                                                                                                                                  </div>
                                                                                                                                                                          <nav className="p-4 flex-1 space-y-1">
                                                                                                                                                                                    <Link href={`/${params.slug}/dashboard`} className="flex items-center gap-3 px-3 py-2 rounded-lg bg-white/5 text-white font-medium text-sm">
                                                                                                                                                                                                <BookOpen size={16} /> Dashboard
                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                    <Link href={`/${params.slug}/conteudo`} className="flex items-center gap-3 px-3 py-2 rounded-lg text-zinc-400 hover:bg-white/5 hover:text-white transition-all text-sm">
                                                                                                                                                                                                                                <Play size={16} /> Meus Cursos
                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                    <Link href={`/${params.slug}/perfil`} className="flex items-center gap-3 px-3 py-2 rounded-lg text-zinc-400 hover:bg-white/5 hover:text-white transition-all text-sm">
                                                                                                                                                                                                                                                                <User size={16} /> Meu Perfil
                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                  </nav>
                                                                                                                                                                                                                                                                                          <div className="p-4 border-t border-white/5">
                                                                                                                                                                                                                                                                                                    <Link href={`/${params.slug}/login`} className="flex items-center gap-3 px-3 py-2 rounded-lg text-zinc-500 hover:text-red-400 transition-all text-sm">
                                                                                                                                                                                                                                                                                                                <LogOut size={16} /> Sair
                                                                                                                                                                                                                                                                                                                          </Link>
                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                        </aside>
                                                                                                                                                                                                                                                                                                                                              <main className="flex-1 overflow-y-auto">
                                                                                                                                                                                                                                                                                                                                                      <header className="border-b border-white/5 px-8 py-4 flex items-center justify-between">
                                                                                                                                                                                                                                                                                                                                                                <h1 className="text-lg font-semibold">Dashboard</h1>
                                                                                                                                                                                                                                                                                                                                                                        </header>
                                                                                                                                                                                                                                                                                                                                                                                <div className="p-8 space-y-10">
                                                                                                                                                                                                                                                                                                                                                                                          <section>
                                                                                                                                                                                                                                                                                                                                                                                                      <h2 className="text-2xl font-bold mb-2">Bem-vindo de volta!</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-zinc-500">Continue de onde parou ou explore novos cursos.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                            </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3 className="text-xl font-bold mb-6">Meus Cursos</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {courses.length === 0 ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <div className="bg-zinc-900 rounded-2xl border border-white/5 p-12 text-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <BookOpen className="w-12 h-12 text-zinc-700 mx-auto mb-4" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="text-zinc-500">Nenhum curso disponivel ainda.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-5">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {(courses as any[]).map((course) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Link key={course.id} href={`/${params.slug}/curso/${course.id}`} className="group block">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-zinc-900 rounded-xl overflow-hidden border border-white/5 hover:border-white/20 transition-all">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="aspect-video bg-zinc-800 relative overflow-hidden">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {course.thumbnail ? (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <img src={course.thumbnail} alt={course.title} className="w-full h-full object-cover" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ) : (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div className="w-full h-full flex items-center justify-center">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <Play className="w-10 h-10 text-zinc-600" />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {course.is_coming_soon && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className="absolute top-2 right-2 bg-yellow-500 text-black text-xs font-bold px-2 py-1 rounded">EM BREVE</span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="p-4">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h4 className="font-semibold text-sm group-hover:text-blue-400 transition-colors">{course.title}</h4>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {course.description && <p className="text-zinc-500 text-xs mt-1 line-clamp-2">{course.description}</p>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </Link>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
